### ISSUE TITLE
NotAuthorized exception on dataset that should be readable

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-grace-period#1]
We have a ckan instance running, with some published datasets, available without logging in ckan.

Once the grace_period plugin is installed, opening a dataset results in an "internal server error" and the log reports:
```
021-05-04 18:51:54,661 ERROR [ckan.config.middleware.flask_app] Action auth_resource_show requires an authenticated user
Traceback (most recent call last):
  File "/home/geosol/prj/crea_run/venv2/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geosol/prj/crea_run/venv2/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/ssd2/homeext/geosol/prj/crea_run/ckan/ckan/config/middleware/../../views/dataset.py", line 500, in read
    u'id': resource[u'id']
  File "/mnt/ssd2/homeext/geosol/prj/crea_run/ckan/ckan/logic/__init__.py", line 477, in wrapped
    result = _action(context, data_dict, **kw)
  File "/mnt/ssd2/homeext/geosol/prj/crea_run/ckan/ckan/logic/action/get.py", line 1141, in resource_view_list
    _check_access('resource_view_list', context, data_dict)
  File "/mnt/ssd2/homeext/geosol/prj/crea_run/ckan/ckan/logic/__init__.py", line 313, in check_access
    raise NotAuthorized(msg)
```

**Comment by etj** [comment]
Required base results when accessing a resource:

`NOGRACE` -> resource with no grace period set
`EXGRACE` -> resource with grace period ex
`INGRACE` -> resource within its  grace period 

```
                   expected got received
RESULT NOGRACE ADMIN    200 got 200
RESULT NOGRACE OWNER    200 got 200
RESULT NOGRACE COLLAB   200 got 200
RESULT NOGRACE ORGADMIN 200 got 200
RESULT NOGRACE ORGUSER  200 got 200
RESULT NOGRACE AUTH     200 got 200
RESULT NOGRACE ANON     200 got 200

RESULT EXGRACE ADMIN    200 got 200
RESULT EXGRACE OWNER    200 got 200
RESULT EXGRACE COLLAB   200 got 200
RESULT EXGRACE ORGADMIN 200 got 200
RESULT EXGRACE ORGUSER  200 got 200
RESULT EXGRACE AUTH     200 got 200
RESULT EXGRACE ANON     200 got 200

RESULT INGRACE ADMIN    200 got 200
RESULT INGRACE OWNER    200 got 200
RESULT INGRACE COLLAB   200 got 200
RESULT INGRACE ORGADMIN 200 got 200
RESULT INGRACE ORGUSER  404 got 404
RESULT INGRACE AUTH     404 got 404
RESULT INGRACE ANON     404 got 404
```

**Comment by etj** [comment]
Required base results when accessing a dataset:

Result at the moment are:
```
=== CHECK DATASET ACCESS

RESULT DATASET ADMIN    200 got 200
RESULT DATASET OWNER    200 got 200
RESULT DATASET COLLAB   200 got 200
RESULT DATASET ORGADMIN 200 got 200
RESULT DATASET ORGUSER  200 got 500
RESULT DATASET AUTH     200 got 500
RESULT DATASET ANON     200 got 500
```

We need 200 for all requests:
```
=== CHECK DATASET ACCESS

RESULT DATASET ADMIN    200 got 200
RESULT DATASET OWNER    200 got 200
RESULT DATASET COLLAB   200 got 200
RESULT DATASET ORGADMIN 200 got 200
RESULT DATASET ORGUSER  200 got 200
RESULT DATASET AUTH     200 got 200
RESULT DATASET ANON     200 got 200
```

**Comment by korotkin** [comment]
NotAuthorized exception is a ckan-core designed feature for handle unauthorized attempts to access
Task after the start is re-qualified into - the user has access to the blocked resource
